name: loan
version: 1.0.0
source: contracts
packages:
  - path: contracts/LoanFactory.sol
    contractName: LoanFactory
    customChecksum: 0x7aa8d8d487267cae72cb826e519a194926045204fb89f7c42f6f39ba09f2e339
  - path: contracts/Loan.sol
    contractName: Loan
    customChecksum: 0xdd066e446ab555da51a4cee831f11e99e6ee48844ff0a0f8c3675027cdf89da1
  - path: contracts/libraries/LoanLib.sol
    contractName: LoanLib
    customChecksum: 0x509e63a89f3d76b5bb70610b6bf59bdb38050697efa496256a479d4ad252da5d
customDescription: Loan Artifacts and ABIs
