name: loan
version: 1.0.0
source: contracts
packages:
  - path: contracts/LoanFactory.sol
    contractName: LoanFactory
    customChecksum: 0x0
  - path: contracts/Loan.sol
    contractName: Loan
    customChecksum: 0x0
  - path: contracts/libraries/LoanLib.sol
    contractName: LoanLib
    customChecksum: 0x0
customDescription: Loan Artifacts and ABIs
